const SEARCH = 'SEARCH'
const SEARCH_PROGRESS = 'SEARCH_PROGRESS'
const SEARCH_FINISHED = 'SEARCH_FINISHED'
const SEARCH_ERROR = 'SEARCH_ERROR'

const LOAD_GRAPH_DATA = 'LOAD_GRAPH_DATA'
const UPDATE_GRAPH_DATA = 'UPDATE_GRAPH_DATA'

const SET_PACKAGE_INFO = 'SET_PACKAGE_INFO'
const CLEAR_PACKAGE_INFO = 'CLEAR_PACKAGE_INFO'

export {
    SEARCH,
    SEARCH_PROGRESS,
    SEARCH_FINISHED,
    SEARCH_ERROR,
    LOAD_GRAPH_DATA,
    UPDATE_GRAPH_DATA,
    SET_PACKAGE_INFO,
    CLEAR_PACKAGE_INFO
}
