const SEARCH_STARTED = 'SEARCH_STARTED'
const SEARCH_PROGRESS = 'SEARCH_PROGRESS'
const SEARCH_FINISHED = 'SEARCH_FINISHED'
const SEARCH_ERROR = 'SEARCH_ERROR'
const SEARCH_UPDATE_CACHE_SIZE = 'SEARCH_UPDATE_CACHE_SIZE'

const LOAD_GRAPH_DATA = 'LOAD_GRAPH_DATA'
const UPDATE_GRAPH_DATA = 'UPDATE_GRAPH_DATA'

const PACKAGE_INFO_SEARCH_START = 'PACKAGE_INFO_SEARCH_START'
const PACKAGE_INFO_ERROR = 'PACKAGE_INFO_ERROR'
const SET_PACKAGE_INFO = 'SET_PACKAGE_INFO'
const CLEAR_PACKAGE_INFO = 'CLEAR_PACKAGE_INFO'

// prettier-ignore
export {
    SEARCH_STARTED,
    SEARCH_PROGRESS,
    SEARCH_FINISHED,
    SEARCH_ERROR,
    SEARCH_UPDATE_CACHE_SIZE,

    LOAD_GRAPH_DATA,
    UPDATE_GRAPH_DATA,

    PACKAGE_INFO_SEARCH_START,
    PACKAGE_INFO_ERROR,
    SET_PACKAGE_INFO,
    CLEAR_PACKAGE_INFO
}
